export type TourTabId =
  'overview' | 'render' | 'composition' | 'cost' | 'operations' | 'architecture';

export type TourCompletion =
  | { type: 'manual' }
  | { type: 'click' }
  | { type: 'input'; validate?: (element: HTMLInputElement | HTMLSelectElement) => boolean }
  | { type: 'event'; name: string }
  | { type: 'route'; pathname: string }
  | {
      type: 'state';
      name: string;
      matches: (detail: unknown) => boolean;
      rejects?: (detail: unknown) => boolean;
      retryStep?: number;
    };

export type InterviewTourStep = {
  id: string;
  target: `[data-tour="${string}"]`;
  title: string;
  instruction: string;
  completion: TourCompletion;
  tab: TourTabId;
  placement?: 'top' | 'right' | 'bottom' | 'left';
  pathname?: '/' | '/design-system' | '/api-reference';
};

export const interviewTourSteps: InterviewTourStep[] = [
  {
    id: 'overview-summary',
    target: '[data-tour="overview-summary"]',
    title: '認識影音營運後台',
    instruction: '先看平台範圍，再進入實際操作。',
    completion: { type: 'manual' },
    tab: 'overview',
    placement: 'left',
  },
  {
    id: 'open-workbench',
    target: '[data-tour="tab-render"]',
    title: '進入影音工作台',
    instruction: '點擊頁籤，開始一次真實轉檔。',
    completion: { type: 'click' },
    tab: 'overview',
    placement: 'right',
  },
  {
    id: 'choose-source',
    target: '[data-tour="choose-source"]',
    title: '選擇來源影片',
    instruction: '示範影片已就緒。直接使用，或換成自己的影片。',
    completion: { type: 'click' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'adjust-quality',
    target: '[data-tour="adjust-crf"]',
    title: '設定畫質',
    instruction: 'CRF 越低，輸出品質與檔案容量通常越高。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'choose-preset',
    target: '[data-tour="choose-preset"]',
    title: '選擇編碼速度',
    instruction: '導覽採用 Ultrafast，縮短現場等待時間。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'toggle-faststart',
    target: '[data-tour="toggle-faststart"]',
    title: '改善啟播',
    instruction: 'Faststart 已採用推薦設定，可直接下一步。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'choose-delivery-format',
    target: '[data-tour="delivery-format"]',
    title: '選擇串流交付格式',
    instruction: '採用 HLS + CMAF，讓所有畫質共用 fragmented MP4 分段規格。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'choose-abr-ladder',
    target: '[data-tour="abr-ladder"]',
    title: '建立多碼率階梯',
    instruction: '一次產生 360p、540p、720p 與 1080p，覆蓋不同網路與裝置。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'choose-vmaf',
    target: '[data-tour="quality-metric"]',
    title: '要求 VMAF 實測',
    instruction: '任務完成後，比較來源與各畫質版本的 VMAF 實測結果。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'submit-render',
    target: '[data-tour="submit-render"]',
    title: '開始轉檔',
    instruction: '送出參數，由後端 FFmpeg 產生 MP4。',
    completion: { type: 'click' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'render-result',
    target: '[data-tour="render-result"]',
    title: '轉檔已交由背景處理',
    instruction: '顯示最多 5 秒進度，接著前往媒體合成；完整成品可在導覽後回來查看。',
    completion: {
      type: 'state',
      name: 'media-lab:render-state',
      matches: (detail) => detail === 'ready',
      rejects: (detail) => detail === 'failed' || detail === 'unavailable',
    },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'switch-rendition',
    target: '[data-tour="rendition-switcher"]',
    title: '切換實際輸出畫質',
    instruction: '在同一任務的四個 Rendition 間切換，確認播放器取得正確成品。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'inspect-manifest',
    target: '[data-tour="hls-manifest"]',
    title: '檢查 HLS Master Playlist',
    instruction: 'Manifest 連結各畫質 Playlist 與 CMAF 分段，是播放器自適應切換的入口。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'inspect-vmaf-results',
    target: '[data-tour="vmaf-results"]',
    title: '用 VMAF 決定畫質階梯',
    instruction: '比較本次實測品質、碼率與成本，保留真正有感的 Rendition。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'inspect-probe-evidence',
    target: '[data-tour="evidence-probe"]',
    title: '核對來源媒體規格',
    instruction: '查看 ffprobe 實測的編碼、解析度、幀率、長度、碼率與串流數。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'inspect-gop-evidence',
    target: '[data-tour="evidence-gop"]',
    title: '核對跳轉間隔',
    instruction: '以 GOP 與幀率算出關鍵影格間隔，對齊兩秒 CMAF 分段。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'inspect-sync-evidence',
    target: '[data-tour="evidence-sync"]',
    title: '核對音畫同步',
    instruction: '確認幀率模式、音訊取樣率及音畫長度差。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'inspect-playback-evidence',
    target: '[data-tour="evidence-playback"]',
    title: '驗證成品可播放',
    instruction: '後端重新讀取成品，確認容器可解封裝且播放器能載入。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'inspect-watermark-evidence',
    target: '[data-tour="evidence-watermark"]',
    title: '確認本次水印模式',
    instruction: '收據顯示後端本次實際採用的水印處理模式。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'inspect-delivery-evidence',
    target: '[data-tour="evidence-delivery"]',
    title: '盤點串流交付檔案',
    instruction: '核對 Playlist 與 fragmented MP4 分段的實際產出數量。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'inspect-processing-receipt',
    target: '[data-tour="processing-receipt"]',
    title: '保存可追溯處理收據',
    instruction: '指令、Request ID、Manifest 與成品雜湊共同記錄本次交付。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'open-composition',
    target: '[data-tour="tab-composition"]',
    title: '前往媒體合成',
    instruction: '查看字幕、精靈圖與圖層時間軸。',
    completion: { type: 'click' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'inspect-composition',
    target: '[data-tour="composition-options"]',
    title: '選擇合成方式',
    instruction: '選擇浮水印後，預覽右上角會立即顯示效果。',
    completion: { type: 'manual' },
    tab: 'composition',
    placement: 'left',
  },
  {
    id: 'composition-preview',
    target: '[data-tour="composition-preview"]',
    title: '確認即時預覽',
    instruction: '同一支電影感素材會立即呈現所選浮水印。',
    completion: { type: 'manual' },
    tab: 'composition',
    placement: 'left',
  },
  {
    id: 'run-composition',
    target: '[data-tour="composition-submit"]',
    title: '執行真實合成',
    instruction: '送出合成任務，產生可播放並可驗證的新影片。',
    completion: { type: 'click' },
    tab: 'composition',
    placement: 'right',
  },
  {
    id: 'composition-result',
    target: '[data-tour="composition-result"]',
    title: '查看後端成品',
    instruction: '這是 FFmpeg 實際輸出的影片。播放確認後再繼續。',
    completion: { type: 'manual' },
    tab: 'composition',
    placement: 'left',
  },
  {
    id: 'open-design-system',
    target: '[data-tour="open-design-system"]',
    title: '查看設計系統',
    instruction: '接著看產品如何用同一套色彩、字級與互動規則維持一致。',
    completion: { type: 'click' },
    tab: 'composition',
    placement: 'right',
  },
  {
    id: 'design-tokens',
    target: '[data-tour="design-tokens"]',
    title: '明暗主題與文字對比',
    instruction: '色彩依用途命名，文字與互動狀態以 WCAG AA 對比標準檢查。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
    pathname: '/design-system',
  },
  {
    id: 'design-components-tab',
    target: '[data-tour="design-tab-components"]',
    title: '檢查共用元件',
    instruction: '切換到元件頁，查看按鈕、狀態與鍵盤焦點的共用規則。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'bottom',
    pathname: '/design-system',
  },
  {
    id: 'design-components',
    target: '[data-tour="design-components"]',
    title: '共用元件與操作狀態',
    instruction: '按鈕、狀態、指標與進度採用一致的層級與文字標示。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'left',
    pathname: '/design-system',
  },
  {
    id: 'design-usage-tab',
    target: '[data-tour="design-tab-usage"]',
    title: '查看實際採用',
    instruction: '切換到產品採用，確認這些規則已落在實際功能中。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'bottom',
    pathname: '/design-system',
  },
  {
    id: 'design-adoption-map',
    target: '[data-tour="design-adoption-map"]',
    title: '規則如何落到產品',
    instruction: '設計變數形成共用元件，再套用到轉檔、合成與維運畫面。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
    pathname: '/design-system',
  },
  {
    id: 'open-api-reference',
    target: '[data-tour="open-api-reference"]',
    title: '查看 API 文件',
    instruction: '最後確認前端操作如何連到後端合約。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'bottom',
    pathname: '/design-system',
  },
  {
    id: 'api-endpoints',
    target: '[data-tour="api-overview"]',
    title: '完整服務流程',
    instruction: '從素材、任務、事件到成品播放，都有明確端點。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
    pathname: '/api-reference',
  },
  {
    id: 'api-source-upload',
    target: '[data-tour="api-endpoint-1"]',
    title: '第一步：建立來源素材',
    instruction: '上傳介面先驗證格式與大小，再回傳可追蹤的媒體識別碼。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'right',
    pathname: '/api-reference',
  },
  {
    id: 'api-job-command',
    target: '[data-tour="api-endpoint-4"]',
    title: '第二步：建立處理任務',
    instruction: '同一個請求只會建立一份任務，避免重複執行與重複計費。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'left',
    pathname: '/api-reference',
  },
  {
    id: 'api-event-stream',
    target: '[data-tour="api-endpoint-6"]',
    title: '第三步：持續回報進度',
    instruction: '事件串流可從中斷位置接續，讓介面恢復後仍能取得完整狀態。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'right',
    pathname: '/api-reference',
  },
  {
    id: 'api-artifact-delivery',
    target: '[data-tour="api-endpoint-8"]',
    title: '第四步：交付可播放成品',
    instruction: '成品支援分段載入，可直接預覽、播放與下載。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'left',
    pathname: '/api-reference',
  },
  {
    id: 'api-adaptive-streaming',
    target: '[data-tour="api-endpoint-9"]',
    title: '第五步：交付自適應串流',
    instruction: 'Master Playlist 串起四個畫質，播放器依頻寬切換 CMAF 分段。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'right',
    pathname: '/api-reference',
  },
  {
    id: 'api-guarantees',
    target: '[data-tour="api-guarantees"]',
    title: '確認服務保證',
    instruction: '最後確認處理品質、串流交付、任務可靠性與追蹤隔離。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
    pathname: '/api-reference',
  },
];

export function moveTourStep(current: number, direction: -1 | 1) {
  return Math.min(Math.max(current + direction, 0), interviewTourSteps.length - 1);
}
