export type TourTabId =
  'overview' | 'render' | 'composition' | 'cost' | 'operations' | 'architecture';

export type TourCompletion =
  | { type: 'manual' }
  | { type: 'click' }
  | { type: 'input'; validate?: (element: HTMLInputElement | HTMLSelectElement) => boolean }
  | { type: 'event'; name: string }
  | { type: 'route'; pathname: string }
  | {
      type: 'state';
      name: string;
      matches: (detail: unknown) => boolean;
      rejects?: (detail: unknown) => boolean;
      retryStep?: number;
    };

export type InterviewTourStep = {
  id: string;
  target: `[data-tour="${string}"]`;
  title: string;
  instruction: string;
  completion: TourCompletion;
  tab: TourTabId;
  placement?: 'top' | 'right' | 'bottom' | 'left';
};

export const interviewTourSteps: InterviewTourStep[] = [
  {
    id: 'overview-summary',
    target: '[data-tour="overview-summary"]',
    title: '作品解決什麼？',
    instruction: '從媒體處理、工作流復原到成本治理，先掌握完整範圍。',
    completion: { type: 'manual' },
    tab: 'overview',
    placement: 'left',
  },
  {
    id: 'open-workbench',
    target: '[data-tour="tab-render"]',
    title: '進入影音工作台',
    instruction: '點擊頁籤，開始一次真實轉檔。',
    completion: { type: 'click' },
    tab: 'overview',
    placement: 'right',
  },
  {
    id: 'choose-source',
    target: '[data-tour="choose-source"]',
    title: '選擇來源影片',
    instruction: '示範影片已就緒。直接使用，或換成自己的影片。',
    completion: { type: 'click' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'adjust-quality',
    target: '[data-tour="adjust-crf"]',
    title: '設定畫質',
    instruction: '調整 CRF：越低畫質越高，檔案也越大。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'choose-preset',
    target: '[data-tour="choose-preset"]',
    title: '選擇編碼速度',
    instruction: '切換 Preset，比較速度與壓縮效率。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'toggle-faststart',
    target: '[data-tour="toggle-faststart"]',
    title: '改善啟播',
    instruction: 'Faststart 已採用推薦設定，可直接下一步。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'submit-render',
    target: '[data-tour="submit-render"]',
    title: '開始轉檔',
    instruction: '送出參數，由後端 FFmpeg 產生 MP4。',
    completion: { type: 'click' },
    tab: 'render',
    placement: 'top',
  },
  {
    id: 'render-result',
    target: '[data-tour="render-result"]',
    title: '等待處理完成',
    instruction: 'Worker 正在轉檔與驗證成品。',
    completion: {
      type: 'state',
      name: 'media-lab:render-state',
      matches: (detail) => detail === 'ready',
      rejects: (detail) => detail === 'failed' || detail === 'unavailable',
    },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'artifact-result',
    target: '[data-tour="artifact-result"]',
    title: '這是真實轉檔結果',
    instruction: '影片已由 FFmpeg 產生並開始播放。看完再繼續。',
    completion: { type: 'manual' },
    tab: 'render',
    placement: 'left',
  },
  {
    id: 'open-composition',
    target: '[data-tour="tab-composition"]',
    title: '前往媒體合成',
    instruction: '查看字幕、精靈圖與圖層時間軸。',
    completion: { type: 'click' },
    tab: 'render',
    placement: 'right',
  },
  {
    id: 'inspect-composition',
    target: '[data-tour="composition-options"]',
    title: '選擇合成方式',
    instruction: '選擇浮水印後，預覽右上角會立即顯示效果。',
    completion: { type: 'manual' },
    tab: 'composition',
    placement: 'left',
  },
  {
    id: 'composition-preview',
    target: '[data-tour="composition-preview"]',
    title: '確認即時預覽',
    instruction: '同一支電影感素材會立即呈現所選浮水印。',
    completion: { type: 'manual' },
    tab: 'composition',
    placement: 'left',
  },
  {
    id: 'run-composition',
    target: '[data-tour="composition-submit"]',
    title: '執行真實合成',
    instruction: '按下按鈕，由本機 FFmpeg 產生新影片。',
    completion: { type: 'click' },
    tab: 'composition',
    placement: 'right',
  },
  {
    id: 'composition-result',
    target: '[data-tour="composition-result"]',
    title: '查看後端成品',
    instruction: '這是 FFmpeg 實際輸出的影片。播放確認後再繼續。',
    completion: { type: 'manual' },
    tab: 'composition',
    placement: 'left',
  },
  {
    id: 'open-cost',
    target: '[data-tour="tab-cost"]',
    title: '前往人工智慧成本',
    instruction: '查看用量、歸因與預算控制。',
    completion: { type: 'click' },
    tab: 'composition',
    placement: 'right',
  },
  {
    id: 'inspect-cost',
    target: '[data-tour="cost-content"]',
    title: '試算預算決策',
    instruction: '切換情境或預算，查看放行、告警或停止的結果。此處不呼叫 AI。',
    completion: { type: 'manual' },
    tab: 'cost',
    placement: 'left',
  },
  {
    id: 'cost-pipeline',
    target: '[data-tour="cost-pipeline"]',
    title: '理解成本資料流',
    instruction: '請求經過收據標準化、用量帳本與成本歸因。',
    completion: { type: 'manual' },
    tab: 'cost',
    placement: 'top',
  },
  {
    id: 'cost-metrics',
    target: '[data-tour="cost-metrics"]',
    title: '查看預算指標',
    instruction: '總用量與成本共同決定目前預算風險。',
    completion: { type: 'manual' },
    tab: 'cost',
    placement: 'top',
  },
  {
    id: 'cost-receipt',
    target: '[data-tour="cost-receipt"]',
    title: '查看歸因收據',
    instruction: '每筆估算都能追溯到模型、工作區與專案。',
    completion: { type: 'manual' },
    tab: 'cost',
    placement: 'top',
  },
  {
    id: 'open-operations',
    target: '[data-tour="tab-operations"]',
    title: '前往維運證據',
    instruction: '查看任務追蹤、復原與驗證。',
    completion: { type: 'click' },
    tab: 'cost',
    placement: 'right',
  },
  {
    id: 'inspect-operations',
    target: '[data-tour="operations-content"]',
    title: '讀取真實維運資料',
    instruction: '按下按鈕，直接向本機 API 取得執行快照。',
    completion: { type: 'click' },
    tab: 'operations',
    placement: 'left',
  },
  {
    id: 'operations-result',
    target: '[data-tour="operations-result"]',
    title: '理解維運結果',
    instruction: '這些數字來自目前執行中的後端，不是固定文案。',
    completion: { type: 'manual' },
    tab: 'operations',
    placement: 'left',
  },
  {
    id: 'operations-targets',
    target: '[data-tour="operations-targets"]',
    title: '檢查服務目標',
    instruction: '這些是設計目標，不冒充歷史流量實績。',
    completion: { type: 'manual' },
    tab: 'operations',
    placement: 'top',
  },
  {
    id: 'operations-trace',
    target: '[data-tour="operations-trace"]',
    title: '走完證據鏈',
    instruction: '由請求追蹤到任務、狀態、成品與成本。',
    completion: { type: 'manual' },
    tab: 'operations',
    placement: 'top',
  },
  {
    id: 'open-architecture',
    target: '[data-tour="tab-architecture"]',
    title: '前往系統架構',
    instruction: '檢視前端、API、Worker 與成品服務。',
    completion: { type: 'click' },
    tab: 'operations',
    placement: 'right',
  },
  {
    id: 'inspect-architecture',
    target: '[data-tour="architecture-content"]',
    title: '掌握責任邊界',
    instruction: '介面送出合約，Worker 產生成品，靜態服務負責播放。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'left',
  },
  {
    id: 'open-design-system',
    target: '[data-tour="open-design-system"]',
    title: '查看設計系統',
    instruction: '進一步確認色彩、字級與元件是否一致。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'right',
  },
  {
    id: 'design-tokens',
    target: '[data-tour="design-tokens"]',
    title: '語意設計變數',
    instruction: '明暗主題共用角色命名，並分別通過對比檢查。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
  },
  {
    id: 'design-components-tab',
    target: '[data-tour="design-tab-components"]',
    title: '查看共用元件',
    instruction: '切換到共用元件，檢查互動與狀態。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'bottom',
  },
  {
    id: 'design-components',
    target: '[data-tour="design-components"]',
    title: '共用元件狀態',
    instruction: '按鈕、徽章、指標與進度使用相同規則。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
  },
  {
    id: 'design-usage-tab',
    target: '[data-tour="design-tab-usage"]',
    title: '查看產品採用',
    instruction: '切換到產品採用，確認元件實際用在哪裡。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'bottom',
  },
  {
    id: 'design-usage',
    target: '[data-tour="design-usage"]',
    title: '從規範回到產品',
    instruction: '每個元件都能追溯到真實產品介面。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
  },
  {
    id: 'open-api-reference',
    target: '[data-tour="open-api-reference"]',
    title: '查看介面規格',
    instruction: '最後確認前端操作如何連到後端合約。',
    completion: { type: 'click' },
    tab: 'architecture',
    placement: 'bottom',
  },
  {
    id: 'api-endpoints',
    target: '[data-tour="api-endpoints"]',
    title: '完整 API 流程',
    instruction: '從素材、任務、事件到成品播放，都有明確端點。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
  },
  {
    id: 'api-guarantees',
    target: '[data-tour="api-guarantees"]',
    title: '交付與復原保證',
    instruction: '用冪等、重播、雜湊與租戶隔離完成整條證據鏈。',
    completion: { type: 'manual' },
    tab: 'architecture',
    placement: 'top',
  },
];

export function moveTourStep(current: number, direction: -1 | 1) {
  return Math.min(Math.max(current + direction, 0), interviewTourSteps.length - 1);
}
